name: Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch: {}  

permissions:
  contents: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        sudo apt -y update
        sudo apt -y upgrade
        sudo apt -y install pandoc
        pandoc -v
        bash ./build.sh
        ls -l dist
        ls -l zip
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add dist -f
        git commit -m gh-pages-split
        git subtree split --prefix dist -b gh-pages-split
        git push origin gh-pages-split:gh-pages -f
